Repository alsqhd/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#11 [iOS] 모델 설계 및 Mock Data 생성
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/IssueList/Model/Issue.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/IssueListMockData.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Label.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Milestone.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/User.swift
Labels: feature, iOS, question

#24 Be/17/issue list
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserResponse.java
Labels: backend

#29 feat: 이슈 상세 목업 API
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/CommentResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/Emoji.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
Labels: backend

#30 [BE] IssueResponse의 List Set으로 변경
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueResponse.java
Labels: backend

#31 [BE] issue 상태 patch api
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueStateRequest.java
Labels: backend

#33 [BE] emoji 어노테이션 변경 및 CommentResponse에서 사용하는 자료구조 변경
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/CommentResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/Emoji.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
Labels: backend

#40 [FE] 아이콘, 버튼 추가 LoginPage 짧게 구현 #16
  fe/client/package.json
  fe/client/src/App.tsx
  fe/client/src/Icons/AlertCircle.svg
  fe/client/src/Icons/Clip.svg
  fe/client/src/Icons/Close.svg
  fe/client/src/Icons/CloseBox.svg
  fe/client/src/Icons/Edit.svg
  fe/client/src/Icons/Emoji.svg
  fe/client/src/Icons/Label.svg
  fe/client/src/Icons/LargeLogo.svg
  fe/client/src/Icons/MediumLogo.svg
  fe/client/src/Icons/Milestone.svg
  fe/client/src/Icons/Plus.svg
  fe/client/src/Icons/Refresh.svg
  fe/client/src/Icons/Search.svg
  fe/client/src/Icons/Trash.svg
  fe/client/src/Pages/LoginPage.tsx
  fe/client/src/components/common/IconButton.tsx
Labels: Component, frontend

#37 feat: 라벨 요청 목업 API
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelDummyData.java
Labels: backend

#32 [iOS] Issue 목록 테이블 뷰 작업
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIColor+hexToUIColor.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UILabel+AddLineSpacing.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UINibCreatable.swift
  ios/IssueTracker/IssueTracker/IssueList/View/IssueCell.swift
  ios/IssueTracker/IssueTracker/IssueList/View/IssueCell.xib
  ios/IssueTracker/IssueTracker/IssueList/View/LabelView.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueDataSource.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueTableDelegate.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
Labels: iOS

#45 [BE] 라벨 더미데이터Issue에서도 재활용 할 수 있도록 수정
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelDummyData.java
Labels: backend

#39 feat: asignee 조회 목업 api 작성
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserDummyData.java
Labels: backend

#38 feat: 마일스톤 요청 목업 API
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneDummyData.java
Labels: backend

#52 [iOS] Test 코드 작성
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueViewModelTests/Info.plist
  ios/IssueTracker/IssueViewModelTests/IssueViewModelTests.swift
  ios/IssueTracker/UtilityTests/Info.plist
  ios/IssueTracker/UtilityTests/UtilityTests.swift
Labels: iOS

#55 feat: Labels, MileStones Count mockApi
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserController.java
Labels: backend

#54 [BE] 첨부파일 목업 api 추가
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileResponse.java
  be/issue-tracker-be/src/main/resources/static/images/AI7.png
Labels: backend

#59 [BE] 파일 업로드 컨트롤러 수정
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/MultipartFileNotFoundException.java
  be/issue-tracker-be/src/main/resources/application.properties
Labels: backend

#66 [BE] 이슈 post, put 목업
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueRequest.java
Labels: backend

#68 [iOS] 이슈 편집 기능
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueList/Utility/Notification+Name.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UILabel+AddLineSpacing.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIView+HiddenWithAnimation.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueTableDelegate.swift
Labels: feature, iOS

#70 [BE] Response 래핑
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/CommentResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/FileResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDetailResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/IssueResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelsCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/LabelsCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStoneResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStonesCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/MileStonesCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/UserResponses.java
Labels: backend

#71 [BE] 공통 예외 핸들러 추가
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/CommonExceptionHandler.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/ErrorResponse.java
Labels: backend

#80 [BE] validtaion 수정
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/controller/CommonExceptionHandler.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/dto/ErrorResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueStateRequest.java
Labels: backend

#89 [BE] 사용자 프로필 이미지 추가
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/controller/UserDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponse.java
  be/issue-tracker-be/src/main/resources/static/images/소라게.jpg
Labels: backend

#91 [BE] 이슈 카운트 추가
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponses.java
Labels: backend

#82 [iOS] Navigation, TabBar
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Application/AppDelegate.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/Flow/SceneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIBarButtonItem+setTitle.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/ViewControllerIdentifierable.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/SupportingFiles/SceneDelegate.swift
Labels: feature, iOS

#117 [BE] 리뷰반영
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/dto/FileResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponse.java
Labels: backend

#116 [BE] 레이블 CRUD
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/vo/Emoji.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/controller/CommonExceptionHandler.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/dto/ErrorResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/exception/EntityNotFoundException.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/FileController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/FileDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/MultipartFileNotFoundException.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/dto/FileResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/dto/FileResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueDetailResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueStateRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/controller/LabelController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/controller/LabelDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/domain/Label.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/domain/Labels.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelsCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelsCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/service/LabelService.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/controller/UserController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/controller/UserDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponses.java
  be/issue-tracker-be/src/main/resources/application.properties
  be/issue-tracker-be/src/main/resources/static/images/AI7.png
  be/issue-tracker-be/src/main/resources/static/images/소라게.jpg
  be/issue-tracker-be/src/test/java/com/codesquad/issuetracker/label/service/LabelServiceTest.java
Labels: backend

#107 [iOS] network 연결 작업
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Issue.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/IssueListMockData.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Label.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Milestone.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/User.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/Network/NetworkComponents.swift
  ios/IssueTracker/IssueTracker/Network/NetworkService.swift
Labels: feature, iOS

#126 [FE] 이슈리스트 필터링 구현
  fe/client/src/Pages/CreateIssuePage.tsx
  fe/client/src/Pages/IssueListPage.tsx
  fe/client/src/components/common/FilterTab.tsx
  fe/client/src/components/common/InputField.tsx
  fe/client/src/components/common/Label.tsx
  fe/client/src/components/common/LabelMilestoneToggle.tsx
  fe/client/src/components/common/atoms/filterAtom.ts
  fe/client/src/components/common/atoms/issueInputAtom.ts
  fe/client/src/components/common/types/APIType.ts
  fe/client/src/components/createIssue/FilterItem.tsx
  fe/client/src/components/createIssue/SendButton.tsx
  fe/client/src/components/createIssue/Tabs.tsx
  fe/client/src/components/createIssue/TitleInput.tsx
  fe/client/src/components/issueList/FilterItem.tsx
  fe/client/src/components/issueList/HeadContent.tsx
  fe/client/src/components/issueList/IssueList.tsx
  fe/client/src/components/issueList/IssueStateChangeFilter.tsx
  fe/client/src/components/issueList/ListHeader.tsx
  fe/client/src/components/issueList/ListItem.tsx
  fe/client/src/utils/API.ts
  fe/client/src/utils/commonUtils.ts
  fe/client/src/utils/functionalUtils.ts
  fe/client/src/utils/hook/useRecoilInput.ts
  fe/client/src/utils/myRecoil/atom.ts
  fe/client/src/utils/myRecoil/useRecoilState.tsx
Labels: feature, frontend

#130 [FE] label기능 삭제기능 제외하고 구현
  fe/client/src/Pages/LabelListPage.tsx
  fe/client/src/components/common/types/APIType.ts
  fe/client/src/components/common/types/LabelType.ts
  fe/client/src/components/labelList/LabelCreate.tsx
  fe/client/src/components/labelList/LabelEditItem.tsx
  fe/client/src/components/labelList/LabelSwitching.tsx
  fe/client/src/components/labelList/NewLabel.tsx
  fe/client/src/utils/API.ts
  fe/client/src/utils/hook/useInput.ts
Labels: feature, frontend

#133 [FE] 마일스톤 추가, 수정, 닫기 구현
  fe/client/src/Pages/IssueListPage.tsx
  fe/client/src/Pages/MilestoneListPage.tsx
  fe/client/src/components/common/types/APIType.ts
  fe/client/src/components/common/types/MilestoneType.ts
  fe/client/src/components/labelList/LabelCreate.tsx
  fe/client/src/components/labelList/LabelEditItem.tsx
  fe/client/src/components/milestoneList/MilestoneCreate.tsx
  fe/client/src/components/milestoneList/MilestoneEditItem.tsx
  fe/client/src/components/milestoneList/MilestoneItem.tsx
  fe/client/src/components/milestoneList/MilestoneSwitching.tsx
  fe/client/src/components/milestoneList/NewMilestone.tsx
  fe/client/src/utils/API.ts
Labels: feature, frontend

#137 [FE] 이슈디테일 페이지 버튼 토글 추가
  fe/client/src/App.tsx
  fe/client/src/Icons/Emoji.svg
  fe/client/src/Pages/CreateIssuePage.tsx
  fe/client/src/Pages/IssueDetailPage.tsx
  fe/client/src/components/common/CommentInput.tsx
  fe/client/src/components/common/Header.tsx
  fe/client/src/components/common/InputField.tsx
  fe/client/src/components/common/baseStyle/baseStyle.ts
  fe/client/src/components/common/types/IssueDetailType.ts
  fe/client/src/components/createIssue/CreateInputs.tsx
  fe/client/src/components/createIssue/FilterItem.tsx
  fe/client/src/components/createIssue/SendButton.tsx
  fe/client/src/components/createIssue/Tabs.tsx
  fe/client/src/components/issueDetail/CommentCreate.tsx
  fe/client/src/components/issueDetail/CommentEdit.tsx
  fe/client/src/components/issueDetail/CommentItem.tsx
  fe/client/src/components/issueDetail/CommentSwitch.tsx
  fe/client/src/components/issueDetail/HeadContent.tsx
  fe/client/src/components/issueList/ListItem.tsx
  fe/client/src/components/labelList/LabelCreate.tsx
  fe/client/src/components/labelList/LabelEditItem.tsx
  fe/client/src/components/milestoneList/MilestoneCreate.tsx
  fe/client/src/utils/API.ts
Labels: feature, frontend

#140 [FE] 제목 편집 기능 구현
  fe/client/src/Pages/IssueDetailPage.tsx
  fe/client/src/components/common/CommentInput.tsx
  fe/client/src/components/common/types/APIType.ts
  fe/client/src/components/issueDetail/CommentCreate.tsx
  fe/client/src/components/issueDetail/HeadContent.tsx
  fe/client/src/utils/API.ts
Labels: feature, frontend

#141 [iOS] Filtering Issue 구현
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/Flow/SceneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueFilter/Model/FilterList.swift
  ios/IssueTracker/IssueTracker/IssueFilter/Model/FilterListMock.swift
  ios/IssueTracker/IssueTracker/IssueFilter/Model/IdentifierModel.swift
  ios/IssueTracker/IssueTracker/IssueFilter/UseCase/FetchFilterUseCase.swift
  ios/IssueTracker/IssueTracker/IssueFilter/UseCase/FilterUseCase.swift
  ios/IssueTracker/IssueTracker/IssueFilter/View/FilterListCell.swift
  ios/IssueTracker/IssueTracker/IssueFilter/View/SectionListCell.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewController/IssueFilterViewController.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewController/IssueFilterViewControllerDelegate.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewModel/FilterViewModel.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/IssueListMockData.swift
  ios/IssueTracker/IssueTracker/IssueList/View/IssueCell.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
Labels: feature, iOS

#146 [iOS] NewIssue, IssueDetail 구현
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/Flow/SceneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueDetail/Model/Comment.swift
  ios/IssueTracker/IssueTracker/IssueDetail/Model/Emoji.swift
  ios/IssueTracker/IssueTracker/IssueDetail/Model/IssueDetail.swift
  ios/IssueTracker/IssueTracker/IssueDetail/View/CommentCell.swift
  ios/IssueTracker/IssueTracker/IssueDetail/View/CommentCell.xib
  ios/IssueTracker/IssueTracker/IssueDetail/View/OpenCloseLabel.swift
  ios/IssueTracker/IssueTracker/IssueDetail/ViewController/IssueDetailViewController.swift
  ios/IssueTracker/IssueTracker/IssueDetail/ViewModel/IssueDetailViewModel.swift
  ios/IssueTracker/IssueTracker/IssueFilter/Model/IdentifierModel.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewController/IssueFilterViewController.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewModel/FilterViewModel.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueDetailUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/IssueListFilterUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/Network/NetworkService.swift
  ios/IssueTracker/IssueTracker/NewIssue/Model/ImageFile.swift
  ios/IssueTracker/IssueTracker/NewIssue/Model/NewIssue.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/NewIssueFilterUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/PostNewIssueUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/UploadImageUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewController/Container/MarkdownViewController.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewController/Container/PreviewViewController.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewController/NewIssueViewController.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewController/TextAreaCheckableDelegate.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewModel/NewIssueViewModel.swift
  ios/IssueTracker/IssueTracker/Utility/DateManagable.swift
  ios/IssueTracker/IssueTracker/Utility/FilterUseCase.swift
  ios/IssueTracker/IssueTracker/Utility/UIBarButtonItem+setTitle.swift
  ios/IssueTracker/IssueTracker/Utility/UIColor+hexToUIColor.swift
  ios/IssueTracker/IssueTracker/Utility/UILabel+AddLineSpacing.swift
  ios/IssueTracker/IssueTracker/Utility/UINibCreatable.swift
  ios/IssueTracker/IssueTracker/Utility/UIView+HiddenWithAnimation.swift
  ios/IssueTracker/IssueTracker/Utility/ViewControllerIdentifierable.swift
  ios/IssueTracker/IssueTrackerUITests/Info.plist
Labels: enhancement, feature, iOS

#151 [iOS- Dumba]/149/issue detail
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/IssueDetail/Model/Comment.swift
  ios/IssueTracker/IssueTracker/IssueDetail/Model/IssueDetailMockData.swift
  ios/IssueTracker/IssueTracker/IssueDetail/View/CommentCell.swift
  ios/IssueTracker/IssueTracker/IssueDetail/View/CommentCell.xib
  ios/IssueTracker/IssueTracker/IssueDetail/View/EmojiLabel.swift
  ios/IssueTracker/IssueTracker/IssueDetail/ViewController/IssueDetailViewController.swift
  ios/IssueTracker/IssueTracker/IssueFilter/UseCase/FetchFilterUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueDetailUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/Network/NetworkService.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/PostNewIssueUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/UploadImageUseCase.swift
  ios/IssueTracker/IssueTracker/SupportingFiles/Assets.xcassets/LoadFail.imageset/Contents.json
  ios/IssueTracker/IssueTracker/SupportingFiles/Assets.xcassets/LoadFail.imageset/LoadFail.jpg
  ios/IssueTracker/IssueTracker/Utility/DateManagable.swift
  ios/IssueTracker/IssueTracker/Utility/UIImageView+imageLoad.swift
Labels: enhancement, iOS

#152 [iOS] OAuth 구현
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/Flow/SceneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueDetail/ViewController/IssueDetailViewController.swift
  ios/IssueTracker/IssueTracker/IssueFilter/UseCase/FetchFilterUseCase.swift
  ios/IssueTracker/IssueTracker/IssueFilter/ViewModel/FilterViewModel.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueDetailUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/Keychain/Keychain.swift
  ios/IssueTracker/IssueTracker/Login/UseCase/KeychainManager.swift
  ios/IssueTracker/IssueTracker/Login/UseCase/LoginManager.swift
  ios/IssueTracker/IssueTracker/Login/UseCase/LoginUseCase.swift
  ios/IssueTracker/IssueTracker/Login/UseCase/MockOAuthManager.swift
  ios/IssueTracker/IssueTracker/Login/UseCase/OAuthManager.swift
  ios/IssueTracker/IssueTracker/Login/ViewController/LoginViewController.swift
  ios/IssueTracker/IssueTracker/Login/ViewController/MyAccountViewController.swift
  ios/IssueTracker/IssueTracker/Login/ViewModel/LoginViewModel.swift
  ios/IssueTracker/IssueTracker/Login/ViewModel/MyAccountViewModel.swift
  ios/IssueTracker/IssueTracker/Network/ClientID.swift
  ios/IssueTracker/IssueTracker/Network/LoginURL.swift
  ios/IssueTracker/IssueTracker/Network/NetworkComponents.swift
  ios/IssueTracker/IssueTracker/Network/NetworkService.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/PostNewIssueUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/UseCase/UploadImageUseCase.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewController/Container/PreviewViewController.swift
  ios/IssueTracker/IssueTracker/NewIssue/ViewModel/NewIssueViewModel.swift
  ios/IssueTracker/IssueTracker/SupportingFiles/Info.plist
  ios/IssueTracker/IssueTracker/Utility/Alertable.swift
Labels: feature, iOS
